/* eslint-disable */
/* tslint:disable */
/*
 * -------------------------------------------------------------------------------------
 * ## THIS FILE WAS GENERATED BY typedapi-client-helpers                              ##
 * ## DO NOT EDIT THIS FILE DIRECTLY                                                  ##
 * ##                                                                                 ##
 * ## AUTHOR: Stef Buurman                                                            ##
 * ## SOURCE: https://github.com/Stef-Buurman/TypedApi/tree/main/npm/typed-api-client ##
 * -------------------------------------------------------------------------------------
 */
import { request } from '../generated/http-client';
import type { RequestParams } from '../generated/http-client';
import type {
  HttpValidationProblemDetails,
  MolenData,
  ProblemDetails,
} from '../generated/data-contracts';
import { handleApiResponse } from 'typedapi-client-helpers';
import type { ApiMethodOptions, ApiResult } from 'typedapi-client-helpers';
import {
  handleGoodResult as typedApiDefaultSuccessHandler,
  handleErrors as typedApiDefaultErrorHandler,
  unknownErrorMessage as typedApiDefaultErrorMessage,
} from '../../Utils/DefaultApiFunctions';

/**
 * No description
 *
 * @tags DB
 * @name DBGetAllDataForDB
 * @request GET:/api/DB/all
 */
export async function dBGetAllDataForDB(
  options: ApiMethodOptions<
    void,
    | HttpValidationProblemDetails
    | ProblemDetails
    | HttpValidationProblemDetails,
    RequestParams
  > = {},
): Promise<
  ApiResult<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >
> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >(
    () =>
      request<
        void,
        | HttpValidationProblemDetails
        | ProblemDetails
        | HttpValidationProblemDetails
      >({
        ...params,
        path: `/api/DB/all`,
        method: 'GET',
      }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags DB
 * @name DBGetPlacesDB
 * @request GET:/api/DB/places
 */
export async function dBGetPlacesDB(
  options: ApiMethodOptions<
    void,
    | HttpValidationProblemDetails
    | ProblemDetails
    | HttpValidationProblemDetails,
    RequestParams
  > = {},
): Promise<
  ApiResult<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >
> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >(
    () =>
      request<
        void,
        | HttpValidationProblemDetails
        | ProblemDetails
        | HttpValidationProblemDetails
      >({
        ...params,
        path: `/api/DB/places`,
        method: 'GET',
      }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags DB
 * @name DBGetMolens
 * @request GET:/api/DB/GetMolens
 */
export async function dBGetMolens(
  options: ApiMethodOptions<
    MolenData[],
    | HttpValidationProblemDetails
    | ProblemDetails
    | HttpValidationProblemDetails,
    RequestParams
  > = {},
): Promise<
  ApiResult<
    MolenData[],
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >
> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<
    MolenData[],
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >(
    () =>
      request<
        MolenData[],
        | HttpValidationProblemDetails
        | ProblemDetails
        | HttpValidationProblemDetails
      >({
        ...params,
        path: `/api/DB/GetMolens`,
        method: 'GET',
        format: 'json',
      }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}
