/* eslint-disable */
/* tslint:disable */
/*
 * -------------------------------------------------------------------------------------
 * ## THIS FILE WAS GENERATED BY typedapi-client-helpers                              ##
 * ## DO NOT EDIT THIS FILE DIRECTLY                                                  ##
 * ##                                                                                 ##
 * ## AUTHOR: Stef Buurman                                                            ##
 * ## SOURCE: https://github.com/Stef-Buurman/TypedApi/tree/main/npm/typed-api-client ##
 * -------------------------------------------------------------------------------------
 */
import { ContentType, request } from '../generated/http-client';
import type { RequestParams } from '../generated/http-client';
import type {
  HttpValidationProblemDetails,
  MolenDeleteMolenImageParams,
  MolenGetAllDisappearedMolensParams,
  MolenGetAllMolenMapDataParams,
  MolenGetAllMolensByProvincieParams,
  MolenGetMolenDataByTBNumberParams,
  MolenGetMolenTypesParams,
  MolenUploadImageParams,
  MolenUploadImagePayload,
  MolenUploadMolensHtmlPayload,
  ProblemDetails,
  UploadDeleteImageReturnType,
} from '../generated/data-contracts';
import { handleApiResponse } from 'typedapi-client-helpers';
import type { ApiMethodOptions, ApiResult } from 'typedapi-client-helpers';
import {
  handleGoodResult as typedApiDefaultSuccessHandler,
  handleErrors as typedApiDefaultErrorHandler,
  unknownErrorMessage as typedApiDefaultErrorMessage,
} from '../../Utils/DefaultApiFunctions';

/**
 * No description
 *
 * @tags Molen
 * @name MolenGetAllMolensByProvincie
 * @request GET:/api/molen/all/{provincie}
 */
export async function molenGetAllMolensByProvincie(
  pathParams: MolenGetAllMolensByProvincieParams,
  options: ApiMethodOptions<
    void,
    | HttpValidationProblemDetails
    | ProblemDetails
    | HttpValidationProblemDetails,
    RequestParams
  > = {},
): Promise<
  ApiResult<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >
> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >(
    () =>
      request<
        void,
        | HttpValidationProblemDetails
        | ProblemDetails
        | HttpValidationProblemDetails
      >({
        ...params,
        path: `/api/molen/all/${encodeURIComponent(String(pathParams['provincie']))}`,
        method: 'GET',
      }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags Molen
 * @name MolenGetAllMolens
 * @request GET:/api/molen/all
 */
export async function molenGetAllMolens(
  options: ApiMethodOptions<
    void,
    | HttpValidationProblemDetails
    | ProblemDetails
    | HttpValidationProblemDetails,
    RequestParams
  > = {},
): Promise<
  ApiResult<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >
> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >(
    () =>
      request<
        void,
        | HttpValidationProblemDetails
        | ProblemDetails
        | HttpValidationProblemDetails
      >({
        ...params,
        path: `/api/molen/all`,
        method: 'GET',
      }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags Molen
 * @name MolenGetAllMolenMapData
 * @request GET:/api/molen/mapdata
 */
export async function molenGetAllMolenMapData(
  query: MolenGetAllMolenMapDataParams = {},
  options: ApiMethodOptions<
    void,
    | HttpValidationProblemDetails
    | ProblemDetails
    | HttpValidationProblemDetails,
    RequestParams
  > = {},
): Promise<
  ApiResult<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >
> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >(
    () =>
      request<
        void,
        | HttpValidationProblemDetails
        | ProblemDetails
        | HttpValidationProblemDetails
      >({
        ...params,
        path: `/api/molen/mapdata`,
        method: 'GET',
        query: query,
      }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags Molen
 * @name MolenGetAllActiveMolens
 * @request GET:/api/molen/active
 */
export async function molenGetAllActiveMolens(
  options: ApiMethodOptions<
    void,
    | HttpValidationProblemDetails
    | ProblemDetails
    | HttpValidationProblemDetails,
    RequestParams
  > = {},
): Promise<
  ApiResult<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >
> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >(
    () =>
      request<
        void,
        | HttpValidationProblemDetails
        | ProblemDetails
        | HttpValidationProblemDetails
      >({
        ...params,
        path: `/api/molen/active`,
        method: 'GET',
      }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags Molen
 * @name MolenGetAllExistingMolens
 * @request GET:/api/molen/existing
 */
export async function molenGetAllExistingMolens(
  options: ApiMethodOptions<
    void,
    | HttpValidationProblemDetails
    | ProblemDetails
    | HttpValidationProblemDetails,
    RequestParams
  > = {},
): Promise<
  ApiResult<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >
> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >(
    () =>
      request<
        void,
        | HttpValidationProblemDetails
        | ProblemDetails
        | HttpValidationProblemDetails
      >({
        ...params,
        path: `/api/molen/existing`,
        method: 'GET',
      }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags Molen
 * @name MolenGetAllDisappearedMolens
 * @request GET:/api/molen/disappeared/{provincie}
 */
export async function molenGetAllDisappearedMolens(
  pathParams: MolenGetAllDisappearedMolensParams,
  options: ApiMethodOptions<
    void,
    | HttpValidationProblemDetails
    | ProblemDetails
    | HttpValidationProblemDetails,
    RequestParams
  > = {},
): Promise<
  ApiResult<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >
> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >(
    () =>
      request<
        void,
        | HttpValidationProblemDetails
        | ProblemDetails
        | HttpValidationProblemDetails
      >({
        ...params,
        path: `/api/molen/disappeared/${encodeURIComponent(String(pathParams['provincie']))}`,
        method: 'GET',
      }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags Molen
 * @name MolenGetAllRemainderMolens
 * @request GET:/api/molen/remainder
 */
export async function molenGetAllRemainderMolens(
  options: ApiMethodOptions<
    void,
    | HttpValidationProblemDetails
    | ProblemDetails
    | HttpValidationProblemDetails,
    RequestParams
  > = {},
): Promise<
  ApiResult<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >
> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >(
    () =>
      request<
        void,
        | HttpValidationProblemDetails
        | ProblemDetails
        | HttpValidationProblemDetails
      >({
        ...params,
        path: `/api/molen/remainder`,
        method: 'GET',
      }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags Molen
 * @name MolenGetAllMolenProvincies
 * @request GET:/api/molen/provincies
 */
export async function molenGetAllMolenProvincies(
  options: ApiMethodOptions<
    void,
    | HttpValidationProblemDetails
    | ProblemDetails
    | HttpValidationProblemDetails,
    RequestParams
  > = {},
): Promise<
  ApiResult<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >
> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >(
    () =>
      request<
        void,
        | HttpValidationProblemDetails
        | ProblemDetails
        | HttpValidationProblemDetails
      >({
        ...params,
        path: `/api/molen/provincies`,
        method: 'GET',
      }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags Molen
 * @name MolenGetMolenFilters
 * @request GET:/api/molen/filters
 */
export async function molenGetMolenFilters(
  options: ApiMethodOptions<
    void,
    | HttpValidationProblemDetails
    | ProblemDetails
    | HttpValidationProblemDetails,
    RequestParams
  > = {},
): Promise<
  ApiResult<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >
> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >(
    () =>
      request<
        void,
        | HttpValidationProblemDetails
        | ProblemDetails
        | HttpValidationProblemDetails
      >({
        ...params,
        path: `/api/molen/filters`,
        method: 'GET',
      }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags Molen
 * @name MolenGetMolenDataByTBNumber
 * @request GET:/api/molen/{tbNumber}
 */
export async function molenGetMolenDataByTBNumber(
  pathParams: MolenGetMolenDataByTBNumberParams,
  options: ApiMethodOptions<
    void,
    | HttpValidationProblemDetails
    | ProblemDetails
    | HttpValidationProblemDetails,
    RequestParams
  > = {},
): Promise<
  ApiResult<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >
> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >(
    () =>
      request<
        void,
        | HttpValidationProblemDetails
        | ProblemDetails
        | HttpValidationProblemDetails
      >({
        ...params,
        path: `/api/molen/${encodeURIComponent(String(pathParams['tbNumber']))}`,
        method: 'GET',
      }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags Molen
 * @name MolenUploadImage
 * @request POST:/api/molen/molen_image/{tbNumber}
 */
export async function molenUploadImage(
  pathParams: MolenUploadImageParams,
  data: MolenUploadImagePayload,
  options: ApiMethodOptions<
    UploadDeleteImageReturnType,
    | HttpValidationProblemDetails
    | ProblemDetails
    | HttpValidationProblemDetails,
    RequestParams
  > = {},
): Promise<
  ApiResult<
    UploadDeleteImageReturnType,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >
> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<
    UploadDeleteImageReturnType,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >(
    () =>
      request<
        UploadDeleteImageReturnType,
        | HttpValidationProblemDetails
        | ProblemDetails
        | HttpValidationProblemDetails
      >({
        ...params,
        path: `/api/molen/molen_image/${encodeURIComponent(String(pathParams['tbNumber']))}`,
        method: 'POST',
        body: data,
        type: ContentType.FormData,
        format: 'json',
      }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags Molen
 * @name MolenUploadMolensHtml
 * @request POST:/api/molen/uploadMolensHtml
 */
export async function molenUploadMolensHtml(
  data: MolenUploadMolensHtmlPayload,
  options: ApiMethodOptions<
    void,
    | HttpValidationProblemDetails
    | ProblemDetails
    | HttpValidationProblemDetails,
    RequestParams
  > = {},
): Promise<
  ApiResult<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >
> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >(
    () =>
      request<
        void,
        | HttpValidationProblemDetails
        | ProblemDetails
        | HttpValidationProblemDetails
      >({
        ...params,
        path: `/api/molen/uploadMolensHtml`,
        method: 'POST',
        body: data,
        type: ContentType.Json,
      }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags Molen
 * @name MolensendMolenHtml
 * @request GET:/api/molen/uploadMolenHtml
 */
export async function molensendMolenHtml(
  options: ApiMethodOptions<
    void,
    | HttpValidationProblemDetails
    | ProblemDetails
    | HttpValidationProblemDetails,
    RequestParams
  > = {},
): Promise<
  ApiResult<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >
> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >(
    () =>
      request<
        void,
        | HttpValidationProblemDetails
        | ProblemDetails
        | HttpValidationProblemDetails
      >({
        ...params,
        path: `/api/molen/uploadMolenHtml`,
        method: 'GET',
      }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags Molen
 * @name MolenDeleteMolenImage
 * @request DELETE:/api/molen/molen_image/{tbNumber}/{imageName}
 */
export async function molenDeleteMolenImage(
  pathParams: MolenDeleteMolenImageParams,
  options: ApiMethodOptions<
    void,
    | HttpValidationProblemDetails
    | ProblemDetails
    | HttpValidationProblemDetails,
    RequestParams
  > = {},
): Promise<
  ApiResult<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >
> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >(
    () =>
      request<
        void,
        | HttpValidationProblemDetails
        | ProblemDetails
        | HttpValidationProblemDetails
      >({
        ...params,
        path: `/api/molen/molen_image/${encodeURIComponent(String(pathParams['tbNumber']))}/${encodeURIComponent(String(pathParams['imageName']))}`,
        method: 'DELETE',
      }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags Molen
 * @name MolenUpdateOldestMolens
 * @request GET:/api/molen/update_oldest_molens
 */
export async function molenUpdateOldestMolens(
  options: ApiMethodOptions<
    void,
    | HttpValidationProblemDetails
    | ProblemDetails
    | HttpValidationProblemDetails,
    RequestParams
  > = {},
): Promise<
  ApiResult<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >
> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >(
    () =>
      request<
        void,
        | HttpValidationProblemDetails
        | ProblemDetails
        | HttpValidationProblemDetails
      >({
        ...params,
        path: `/api/molen/update_oldest_molens`,
        method: 'GET',
      }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags Molen
 * @name MolenGetNewAddedMolens
 * @request GET:/api/molen/search_for_new_molens
 */
export async function molenGetNewAddedMolens(
  options: ApiMethodOptions<
    void,
    | HttpValidationProblemDetails
    | ProblemDetails
    | HttpValidationProblemDetails,
    RequestParams
  > = {},
): Promise<
  ApiResult<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >
> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >(
    () =>
      request<
        void,
        | HttpValidationProblemDetails
        | ProblemDetails
        | HttpValidationProblemDetails
      >({
        ...params,
        path: `/api/molen/search_for_new_molens`,
        method: 'GET',
      }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags Molen
 * @name MolenGetMolenTypes
 * @request GET:/api/molen/read_molen/{tbNumber}
 */
export async function molenGetMolenTypes(
  pathParams: MolenGetMolenTypesParams,
  options: ApiMethodOptions<
    void,
    | HttpValidationProblemDetails
    | ProblemDetails
    | HttpValidationProblemDetails,
    RequestParams
  > = {},
): Promise<
  ApiResult<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >
> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >(
    () =>
      request<
        void,
        | HttpValidationProblemDetails
        | ProblemDetails
        | HttpValidationProblemDetails
      >({
        ...params,
        path: `/api/molen/read_molen/${encodeURIComponent(String(pathParams['tbNumber']))}`,
        method: 'GET',
      }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags Molen
 * @name MolenGetAllMolen
 * @request GET:/api/molen/read_all_molen
 */
export async function molenGetAllMolen(
  options: ApiMethodOptions<
    void,
    | HttpValidationProblemDetails
    | ProblemDetails
    | HttpValidationProblemDetails,
    RequestParams
  > = {},
): Promise<
  ApiResult<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >
> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >(
    () =>
      request<
        void,
        | HttpValidationProblemDetails
        | ProblemDetails
        | HttpValidationProblemDetails
      >({
        ...params,
        path: `/api/molen/read_all_molen`,
        method: 'GET',
      }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}
