/* eslint-disable */
/* tslint:disable */
/*
 * -------------------------------------------------------------------------------------
 * ## THIS FILE WAS GENERATED BY typedapi-client-helpers                              ##
 * ## DO NOT EDIT THIS FILE DIRECTLY                                                  ##
 * ##                                                                                 ##
 * ## AUTHOR: Stef Buurman                                                            ##
 * ## SOURCE: https://github.com/Stef-Buurman/TypedApi/tree/main/npm/typed-api-client ##
 * -------------------------------------------------------------------------------------
 */
import { request } from '../generated/http-client';
import type { RequestParams } from '../generated/http-client';
import type {
  HttpValidationProblemDetails,
  PlacesGetPlacesByInputParams,
  ProblemDetails,
} from '../generated/data-contracts';
import { handleApiResponse } from 'typedapi-client-helpers';
import type { ApiMethodOptions, ApiResult } from 'typedapi-client-helpers';
import {
  handleGoodResult as typedApiDefaultSuccessHandler,
  handleErrors as typedApiDefaultErrorHandler,
  unknownErrorMessage as typedApiDefaultErrorMessage,
} from '../../Utils/DefaultApiFunctions';

/**
 * No description
 *
 * @tags Places
 * @name PlacesReadAllNetherlandsPlaces
 * @request GET:/api/read_all_netherlands_places
 */
export async function placesReadAllNetherlandsPlaces(
  options: ApiMethodOptions<
    void,
    | HttpValidationProblemDetails
    | ProblemDetails
    | HttpValidationProblemDetails,
    RequestParams
  > = {},
): Promise<
  ApiResult<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >
> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >(
    () =>
      request<
        void,
        | HttpValidationProblemDetails
        | ProblemDetails
        | HttpValidationProblemDetails
      >({
        ...params,
        path: `/api/read_all_netherlands_places`,
        method: 'GET',
      }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags Places
 * @name PlacesGetAllNetherlandsPlaces
 * @request GET:/api/get_all_netherlands_places
 */
export async function placesGetAllNetherlandsPlaces(
  options: ApiMethodOptions<
    void,
    | HttpValidationProblemDetails
    | ProblemDetails
    | HttpValidationProblemDetails,
    RequestParams
  > = {},
): Promise<
  ApiResult<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >
> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >(
    () =>
      request<
        void,
        | HttpValidationProblemDetails
        | ProblemDetails
        | HttpValidationProblemDetails
      >({
        ...params,
        path: `/api/get_all_netherlands_places`,
        method: 'GET',
      }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags Places
 * @name PlacesGetPlacesByInput
 * @request GET:/api/get_places_by_input/{input}
 */
export async function placesGetPlacesByInput(
  pathParams: PlacesGetPlacesByInputParams,
  options: ApiMethodOptions<
    void,
    | HttpValidationProblemDetails
    | ProblemDetails
    | HttpValidationProblemDetails,
    RequestParams
  > = {},
): Promise<
  ApiResult<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >
> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<
    void,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >(
    () =>
      request<
        void,
        | HttpValidationProblemDetails
        | ProblemDetails
        | HttpValidationProblemDetails
      >({
        ...params,
        path: `/api/get_places_by_input/${encodeURIComponent(String(pathParams['input']))}`,
        method: 'GET',
      }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}
