/* eslint-disable */
/* tslint:disable */
/*
 * -------------------------------------------------------------------------------------
 * ## THIS FILE WAS GENERATED BY typedapi-client-helpers                              ##
 * ## DO NOT EDIT THIS FILE DIRECTLY                                                  ##
 * ##                                                                                 ##
 * ## AUTHOR: Stef Buurman                                                            ##
 * ## SOURCE: https://github.com/Stef-Buurman/TypedApi/tree/main/npm/typed-api-client ##
 * -------------------------------------------------------------------------------------
 */
import { request } from '../generated/http-client';
import type { RequestParams } from '../generated/http-client';
import type {
  HttpValidationProblemDetails,
  ProblemDetails,
  SearchParams,
  SearchResultsModel,
} from '../generated/data-contracts';
import { handleApiResponse } from 'typedapi-client-helpers';
import type { ApiMethodOptions, ApiResult } from 'typedapi-client-helpers';
import {
  handleGoodResult as typedApiDefaultSuccessHandler,
  handleErrors as typedApiDefaultErrorHandler,
  unknownErrorMessage as typedApiDefaultErrorMessage,
} from '../../Utils/DefaultApiFunctions';

/**
 * No description
 *
 * @tags Search
 * @name Search
 * @request GET:/api/search
 */
export async function search(
  query: SearchParams = {},
  options: ApiMethodOptions<
    SearchResultsModel,
    | HttpValidationProblemDetails
    | ProblemDetails
    | HttpValidationProblemDetails,
    RequestParams
  > = {},
): Promise<
  ApiResult<
    SearchResultsModel,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >
> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<
    SearchResultsModel,
    HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails
  >(
    () =>
      request<
        SearchResultsModel,
        | HttpValidationProblemDetails
        | ProblemDetails
        | HttpValidationProblemDetails
      >({
        ...params,
        path: `/api/search`,
        method: 'GET',
        query: query,
        format: 'json',
      }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}
