name: Deploy program

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    env:
      SSH_USER: ${{ secrets.UPDATE_PROJECT_USER }}
      SSH_IP: ${{ secrets.UPDATE_PROJECT_IP }}
      REMOTE_SCRIPT_PATH: ${{ secrets.UPDATE_PROJECT_FILE_PATH }}
      APP_SETTINGS_PATH: ${{ secrets.APP_SETTINGS_PATH }}
      API_KEY: ${{ secrets.API_KEY }}
      DB_User: ${{ secrets.DB_User }}
      DB_Password: ${{ secrets.DB_Password }}
      DB_Name: ${{ secrets.DB_Name }}
      DB_Port: ${{ secrets.DB_Port }}
      DB_IP: ${{ secrets.DB_IP }}
    steps:
      - uses: actions/checkout@v4

      - name: Test SSH Connection
        run: ssh $SSH_USER@$SSH_IP "echo Connection Successful"

      - name: Set up virtual environment
        run: ssh $SSH_USER@$SSH_IP $REMOTE_SCRIPT_PATH

      - name: Set api key and database connection
        run: |
          ssh "$SSH_USER@$SSH_IP" "cat > $APP_SETTINGS_PATH << EOF
          {
            \"Logging\": {
              \"LogLevel\": {
                \"Default\": \"Information\",
                \"Microsoft.AspNetCore\": \"Warning\"
              }
            },
            \"AllowedHosts\": \"*\",
            \"Kestrel\": {
              \"Endpoints\": {
                \"Http\": {
                  \"Url\": \"http://*:5000\"
                }
              }
            },
            \"FileUploadFilter\": {
              \"Authorization\": \"$API_KEY\"
            },
            \"ConnectionStrings\": {
              \"MolenDatabase\": \"server=$DB_IP;user=$DB_User;password=$DB_Password;database=$DB_Name;port=$DB_Port\"
            }
          }
          EOF"

      - name: Set up virtual environment
        run: ssh $SSH_USER@$SSH_IP $REMOTE_SCRIPT_PATH