name: Python application

on:
    pull_request:
        branches: [ "master" ]

jobs:
  test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: say hello
      run: |
          echo "hallo"
